### ISSUE TITLE
Rework to-do list.

### ISSUE THREAD

**Issue by xapdkop** [xapdkop/BloomFramework#1]
- [x]  make exception class
- [x]  fix Game::init() and Game::destroy() (it's bad idea to init (and quit) all sdl2 modules when creating window)
- [x]  move init to Game constructor
- [x]  add advanced constructor for Game (for example, to choice SDL_Init modules)
- [x]  add support of SDL_Color

**Comment by xapdkop** [comment]
Ok. May I create PR or maybe you want me to add smth?

**Comment by xapdkop** [comment]
merged into original
