### ISSUE TITLE
SDL_mixer support: TO-DO

### ISSUE THREAD

**Issue by xapdkop** [xapdkop/BloomFramework#4]
- [ ] tests
- [x] add optimization (see 21f55f6 commit)
- [x] deny more than 1 copy of `MusicStore`, `SoundStore`, `MusicQueue`, `SoundFull`, `MusicFull` etc.
- [x] one more rework of channels management (store SoundPlayer pointers in vector, create stack for vacant channels, add `channel redistribution` to reduce memory usage)
- [x] add `replay` func for `SoundPlayer`
- [x] add support of fade
- [x] fix broken sld channels (sdl can't automatically allocate channels)

- [x] REWORK!!! Add Sound/Track control class. Rework Track/SoundFX and stores.
- [x] check the correct use and removal of the `SoundChunk`s and `SoundPlayer`s
- [x] add basic music integration
- [x] add basic sound effects integration [1/2]
- [x] add basic sound effects integration [2/2] (~make extended sdl channel support~)
- [x] add music store
- [x] add sounds store
- [x] rework music store (separate store and queue)

- [x] check if all necessary sdl_mixer funcs available
- [x] add auto channels for sounds
- [x] ~add backup manual channel management~
- [x] add playback control (play sound only if it isn't playing)

**Comment by xapdkop** [comment]
Hm, what i meant in "add basic sound effects integration [2/2]"?

**Comment by xapdkop** [comment]
Hey!

**Comment by xapdkop** [comment]
Hey!

**Comment by xapdkop** [comment]
Up!

**Comment by LumpBloom7** [comment]
Awesome!

**Comment by xapdkop** [comment]
omfg @xapdkop, when will be release?

**Comment by xapdkop** [comment]
prepare for release

**Comment by xapdkop** [comment]
finally merged https://github.com/BloomCreativeWorks/BloomFramework/pull/21
